project:
  type: website
  output-dir: docs

website:
  title: "madeleine guyant"
  about: 
    template: trestles
    image-shape: rounded
    image-width: 15em
    links:
      -text: LinkedIn
       href: https://www.linkedin.com/in/madeleineguyant/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



